//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEjemplo1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.comentario = new HashSet<comentario>();
        }
    
        public int cod_articulo { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fec_publicacion { get; set; }
        public string autor { get; set; }
        [AllowHtml]
        public string contenido { get; set; }
        public bool estado { get; set; }
        public string url_img { get; set; }
        [AllowHtml]
        public string resumen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
    }
}
