//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEjemplo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int cod_estudiante { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string carne { get; set; }
        public Nullable<System.DateTime> fec_nacimiento { get; set; }
        public string dpi { get; set; }
    }
}
