//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEjemplo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_venta
    {
        public int cod_det_venta { get; set; }
        public int cod_producto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public int cod_venta { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
